### ISSUE TITLE
Create wiki page with links to useful resources and documentation

### ISSUE THREAD

**Issue by alexchmykhalo** [PLLUG/file-server#3]

**Comment by alexchmykhalo** [comment]
@NeklesaYuri, please take this task and add wiki page with useful links based on our document in Google Docs - [https://docs.google.com/document/d/1qVRCDOt7EjLjxCcPkgPPFdxWBNXm1oQ3tOSxe0PkMU0/edit](https://docs.google.com/document/d/1qVRCDOt7EjLjxCcPkgPPFdxWBNXm1oQ3tOSxe0PkMU0/edit)

when page will be added - just make comment with link here and I will close this task

**Comment by neklesayurii** [comment]
@alexchmykhalo, https://github.com/PLLUG/file-server/wiki/Useful-links
