### ISSUE TITLE
Create documentation that describes requests/responses to/from the server.

### ISSUE THREAD

**Issue by alexchmykhalo** [PLLUG/file-server#8]
- Describe queries to web server and web server responses.
- URL request format
- Behavior when invalid URL is used

**Comment by alexchmykhalo** [comment]
@pgmvp please, add description for URL that will display detailed information about the file. It could be similar to download URL. Example of file info page is here http://download.qt.io/snapshots/qtcreator/master/latest/qt-creator-opensource-windows-x86-master.exe.mirrorlist. This should be also related to @romansavelyev task: Roma, do we have any mockup for info page?

**Comment by romansavelyev** [comment]
not yet.
what do we need in information page?
i'm thinking of some detail information(full name,size,modifications(few last))

also there can be HASH.

maybe we need to add link to some mirror  or similar files.
or something like this.

**Comment by alexchmykhalo** [comment]
@romansavelyev about information: yes, as a described in [documentation](https://github.com/PLLUG/file-server/wiki) we need at least: creation date, modification date, hash in sha1, md5, or some other format.

about mirror links - we could drop that feature for the first version of the server

**Comment by alexchmykhalo** [comment]
as documentation was added, I close this task
